### ISSUE TITLE
Spacing and idents in abstract/acknowledgements

### ISSUE THREAD

**Issue by jordanrhall** [mathematicalmichael/dissertation-template#15]
This is a general issue where some sloppy fixes are pinning things together. How do we make this easy and clean?
Basically, the formatting from the rest of the document isn't getting nicely carried over to these sections. Main issues are both indents and spacing. Indents are not difficult to fix via hard-coding, which we have in abstract.tex. Spacing seems trickier. Here is what I noticed:

- Tried to insert a longer acknowledgements section (for demonstration) by using input command to call a file I made called acknowledgements.tex, identical to what we do with abstract.tex

- Used a \lipsum[] commands to make 2 paragraphs and also used the paragraph indent line we use in the abstract to get indents (this worked)

- First paragraph was double-spaced, the second paragraph ends up single-spaced. I tried fixing for quite a while to no avail.

Help!

**Comment by mathematicalmichael** [comment]
add `\vfill` to the bottom of the section you're including? or `FloatBarrier`. will try and replicate this.

**Comment by mathematicalmichael** [comment]
looks like the aforementioned fix worked. closing.
